Milestone 1: Create data model
Christianib003/Blog-app pull request #1
Opened 2022-11-23 15:08 UTC by Christianib003

- [ ] `Initialiazed` rails app linked with postgresql.
- [ ] Created `User` model and table.
- [ ] Created `Comments`  model and table.
- [ ] Created `Post` model and table.
- [ ] Created `Likes` model and table.
- [ ] `Add foreign keys` to connect the tables.

2022-11-23 15:38 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Christianib003,

Good job so far!
✔️ PostgreSQL is used for DB
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 15:38 UTC, TedLivist commented on db/migrate/20221123133750_create_comments.rb
> +      t.integer :postId
- [ ] Kindly avoid using camel cases for your attribute names. Based on convention this should be the following. Kindly fix that.

  ```
  t.integer :author_id
  t.integer :post_id
  ```

- [ ] Ensure these changes are reflected in the `schema.rb` file.

2022-11-23 15:38 UTC, TedLivist commented on db/migrate/20221123134106_create_posts.rb
> +      t.integer :authorId
- [ ] Kindly change to `author_id`. Ensure you run the migrations and reflect this change in the schema file.

2022-11-23 15:38 UTC, TedLivist commented on db/migrate/20221123134106_create_posts.rb
> +      t.integer :likesCounter
- [ ] Kindly change to `:comments_counter` and `:likes_counter`.

2022-11-23 15:38 UTC, TedLivist commented on db/migrate/20221123134326_create_likes.rb
> +      t.integer :postId
- [ ] These should be `:author_id` and `:post_id` respectively. Kindly fix that.

- [ ] These changes should be reflect in the schema file.

2022-11-23 15:38 UTC, TedLivist commented on db/migrate/20221123133423_create_users.rb
> +      t.integer :postsCounter
- [ ] The attribute should be `:posts_counter`. Kindly fix that.

2022-11-23 15:38 UTC, TedLivist commented on README.md
> +# README
- [ ] Kindly format your README using [the Microverse template](https://github.com/microverseinc/readme-template)

2022-11-24 12:00 UTC, uwadonat approved these changes
## Hi @Christianib003,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
![approval1](https://user-images.githubusercontent.com/65860678/203779276-ee3268fa-abcc-4b39-b7f3-8732881fa7c4.gif)
# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-11-24 12:26 UTC, merged